---
- hosts: all
  name: Install NGINX with custom modules like brotli, oh-my-zsh, fail2ban and acme.sh and setup certificates
  become: true
  vars_files:
    - variables.yml

  roles:
    - role: nginx-brotli
      no_log: false
      debug:
        msg: "NGINX & Brotli role execution is skipped because install_nginx_brotli is set to {{ install_nginx_brotli }}."
      when: install_nginx_brotli | default(false)

    - role: acme.sh
      no_log: false
      debug:
        msg: "ACME.sh role execution is skipped because install_acmesh is set to {{ install_acmesh }}."
      when: install_acmesh | default(false)

    - role: fail2ban
      no_log: false
      debug:
        msg: "Fail2Ban role execution is skipped because install_fail2ban is set to {{ install_fail2ban }}."
      when: install_fail2ban | default(false)
